### ISSUE TITLE
BMI 계산기

### ISSUE THREAD

**Issue by HeegeePark** [HeegeePark/SeSAC#1]
## 📌 Todo

- [x]  레이아웃 및 디자인
- [x]  bmi 계산 메소드
- [x]  키 몸무게 기입하면 알럿으로 BMI 지수 띄우기
- [x]  랜덤 BMI 버튼
- [x]  텍스트필드 문자 입력 방지
- [x]  키/몸무게 텍스트필드 공백 입력 실시간 처리
- [x]  키/몸무게 범위 제한
- [x]  몸무게 텍스트필드 암호화 여부체크에 따른 암호화

### ✅ 기획에 맞게 이미지뷰 오토레이아웃 잡기
- 사진 속 발끝은 텍스트필드에 맞추고, 등은 view trailing에 맞추면서 오토레이아웃을 잡기 쉽지 않았다.
(png 속 등이 이미지 오른쪽 끝부분이 아니었음 ㅠ)
- 막상 이미지뷰 constraints를 잡으면 괜찮았던 왼쪽 레이블들이 hugging 관련 레이아웃 에러를 뿜어내서, 시키는대로 constraint 하나의 priority를 낮추니 해결됨.
  - 충돌되는 제약이 생겨서 그런거 같긴 함.
<img src="https://github.com/HeegeePark/SeSAC/assets/47033052/244524f5-f488-435b-a854-949caf27cf59" width=50% />

**Comment by HeegeePark** [comment]
[📁 프로젝트 바로가기 ](https://github.com/HeegeePark/SeSAC/tree/main/BMICalculator)
