### ISSUE TITLE
240214 Day33 과제

### ISSUE THREAD

**Issue by HeegeePark** [HeegeePark/SeSAC#18]
### Todo | 값 전달 실습
- [ ] 새로운 할 일 값 전달
   - [ ] 마감일 by DatePicker (DateViewController)
   - [ ] 태그 by TextField (TagViewController)
   - [ ] 우선순위 by SegmentControl (PriorityViewController)
   - [ ] 이미지 추가
      - [ ] 개인적인 옵션) 사진 라이브러리 연동
- [ ] 메인화면 UI 구현
