### ISSUE TITLE
BMI 계산기 UserDefaults 활용

### ISSUE THREAD

**Issue by HeegeePark** [HeegeePark/SeSAC#4]
## 📌 Todo
- [x]  UserDefaults를 활용하여 키, 몸무게, 닉네임 저장
- [x]  앱 실행 시, 닉네임은 Label에, 키&몸무게는 텍스트필드에 자동 기입
- [x]  UserDefaults 불러오기 옵셔널 바인딩
- [x]  리셋 버튼 추가하여 키, 몸무게, 닉네임 리셋 구현

**Comment by HeegeePark** [comment]
## 🔨 Issue
### IQKeyboardManager 자동 넘김 핸들링
닉네임 텍스트 필드를 마지막으로 추가하다보니, 몸무게 텍스트필드에서 다음 화살표를 누르면 닉네임 텍스트필드로 자동 연결됨.
안 넘어가게 하고싶음.
<img src="https://github.com/HeegeePark/SeSAC/assets/47033052/203f9ed3-b6c9-481d-b133-d6152a8c09a3" width="30%" />

### IQKeyboardManager Done 처리
IQKeyboardManager를 사용하면 아래 이미지와 같이 Done버튼이 생기는데, 이 버튼도 클릭하면 액션을 감지하여 닉네임 수정을 하고 싶음.
<img src="https://github.com/HeegeePark/SeSAC/assets/47033052/e5223b34-965c-40c9-a950-1db4fe75d3fa" width="30%" />
