### ISSUE TITLE
240126 Day24 과제

### ISSUE THREAD

**Issue by HeegeePark** [HeegeePark/SeSAC#9]
## 📌Todo

- [x]  넷플릭스 CodeBase UI 변경
- [x]  Recap 과제 CodeBase UI 변경
    - [x]  최근 검색어 화면 필수
